# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

services:
  api:
    build:
      context: .
      dockerfile: infrastructure/docker/java.dockerfile
      target: dev
    volumes:
      - ./:/code
    working_dir: /code
    command: "mvn spring-boot:run" # -Dspring-boot.run.profiles=local"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: epaper
      DB_PASSWORD: epaper
      APP_DEBUG: epaper
      MAVEN_OPTS: -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9000"
    tty: true
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - 9000:9000
  postgres:
    image: "postgres:11-alpine"
    environment:
      POSTGRES_DB: epaper
      POSTGRES_USER: epaper
      POSTGRES_PASSWORD: epaper
    hostname: postgres
    networks:
      default:
        aliases:
         - postgresql
    volumes:
      - epaper-psql:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  epaper-psql: